version: '3.8'

services:
  app:
    build: 
      context: .. # ! when building the image, the context is the root of the project
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django_db
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
  
  pgadmin: # for browsing the database in the browser
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # vitst pgadmin at http://localhost:5050
    depends_on: 
      - db

volumes:
  postgres-data: