name: Run Unit Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        env:
          DB_ENGINE: django.db.backends.postgresql
          DB_USER: test_user
          DB_PASSWORD: test_password
          DB_NAME: postgres
          DB_HOST: localhost
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
        run: poetry run pytest 